"""Agent policies, read tools and optional engineering integration boundaries."""

from typing import Protocol

from app.domain.agent import (
    AgentAnswer,
    AgentNotice,
    AgentScope,
    AgentSettings,
    InvestigationReport,
    InvestigationRequest,
)
from app.domain.agent_tools import ReadResult, RevisionQuery, SearchQuery, WorkPackageQuery
from app.domain.models import ProjectSnapshot


class AgentRepository(Protocol):
    def agent_settings(self, project_id: str) -> AgentSettings: ...
    def save_agent_settings(self, project_id: str, settings: AgentSettings) -> None: ...
    def save_investigation(self, request: InvestigationRequest) -> None: ...
    def investigation(self, run_id: str) -> InvestigationRequest: ...
    def save_investigation_report(self, report: InvestigationReport) -> None: ...
    def investigation_report(self, run_id: str) -> InvestigationReport | None: ...
    def save_agent_notice(self, notice: AgentNotice) -> None: ...
    def agent_notices(self, project_id: str) -> list[AgentNotice]: ...


class AgentReadTools(Protocol):
    def project_state(self) -> ReadResult: ...
    def compare_revisions(self, query: RevisionQuery) -> ReadResult: ...
    def bim_changes(self, query: RevisionQuery) -> ReadResult: ...
    def work_package_bindings(self, query: WorkPackageQuery) -> ReadResult: ...
    def persisted_evidence(self) -> ReadResult: ...
    def relevant_documents(self, query: SearchQuery) -> ReadResult: ...


class InvestigationEngine(Protocol):
    mode: str

    def investigate(
        self, instruction: str, scope: AgentScope, tools: AgentReadTools
    ) -> AgentAnswer: ...
    def close(self) -> None: ...


class EngineeringReadPort(Protocol):
    """C supplies persisted normalized comparisons/bindings, never an on-demand write."""

    def changes(
        self, snapshot: ProjectSnapshot, scope: AgentScope, query: RevisionQuery
    ) -> ReadResult: ...
    def bindings(
        self, snapshot: ProjectSnapshot, scope: AgentScope, query: WorkPackageQuery
    ) -> ReadResult: ...
