from contextlib import AbstractContextManager
from typing import Protocol

from app.domain.actions import ActionExecution, ActionProposal, Approval, AuditRecord
from app.domain.events import ProjectEvent
from app.domain.jobs import BIMIndex, CapabilityJob
from app.domain.models import Analysis, Evidence, ProjectSnapshot, ProjectState
from app.domain.retrieval import PreparedEmbeddingIndex
from app.domain.runs import AgentRun, StreamEvent
from app.ports.project_lifecycle import ProjectLifecycleRepository
from app.ports.providers import PreparedDocument


class CoordinationRepository(ProjectLifecycleRepository, Protocol):
    def publish_embeddings(self, prepared: PreparedEmbeddingIndex) -> dict: ...
    def publish_document(self, prepared: PreparedDocument) -> PreparedDocument: ...
    def save_job(self, job: CapabilityJob) -> None: ...
    def job(self, job_id: str) -> CapabilityJob: ...
    def save_bim_index(self, index: BIMIndex) -> None: ...
    def bim_index(self, project_id: str) -> BIMIndex | None: ...
    def save_evidence(self, item: Evidence) -> None: ...
    def evidence(self, project_id: str, source_id: str | None = None) -> list[Evidence]: ...
    def state(self, project_id: str) -> ProjectState: ...
    def projects(self) -> list[ProjectState]: ...
    def save_state(self, state: ProjectState) -> None: ...
    def event(self, event_id: str) -> ProjectEvent | None: ...
    def save_event(self, event: ProjectEvent) -> None: ...
    def events(self, project_id: str) -> list[ProjectEvent]: ...
    def save_snapshot(self, snapshot: ProjectSnapshot) -> None: ...
    def snapshot(self, snapshot_id: str) -> ProjectSnapshot: ...
    def save_analysis(self, analysis: Analysis) -> None: ...
    def analysis(self, analysis_id: str) -> Analysis: ...
    def latest_analysis(self, project_id: str) -> Analysis | None: ...
    def save_run(self, run: AgentRun) -> None: ...
    def run_for_event(self, event_id: str) -> AgentRun: ...
    def pending_runs(self, project_id: str | None = None) -> list[AgentRun]: ...
    def clear_bim_index(self, project_id: str) -> None: ...
    def run(self, run_id: str) -> AgentRun: ...
    def runs(self, project_id: str | None = None) -> list[AgentRun]: ...
    def save_proposal(self, proposal: ActionProposal) -> None: ...
    def proposal(self, proposal_id: str) -> ActionProposal: ...
    def proposals(self, run_id: str) -> list[ActionProposal]: ...
    def save_approval(self, approval: Approval) -> None: ...
    def approvals(self, proposal_id: str) -> list[Approval]: ...
    def execution(self, operation_id: str) -> ActionExecution | None: ...
    def save_execution(self, execution: ActionExecution) -> None: ...
    def audit(self, record: AuditRecord) -> None: ...
    def audits(self, project_id: str) -> list[AuditRecord]: ...
    def emit(self, run_id: str, payload: dict) -> None: ...
    def stream_tail(self, run_id: str, limit: int = 200) -> list[StreamEvent]: ...
    def stream(self, run_id: str, after: int = 0) -> list[StreamEvent]: ...


class RepositoryFactory(Protocol):
    def open(
        self, project_id: str | None = None, *, write: bool = False
    ) -> AbstractContextManager[CoordinationRepository]: ...
