"""Platform-owned publication and execution boundaries for engineering providers."""

from typing import Protocol

from app.domain.engineering import (
    CapabilityCheck,
    CapabilityCheckResult,
    Change,
    Coordination,
    ReCheck,
)
from app.domain.models import Finding


class EngineeringCapability(Protocol):
    name: str
    version: str

    def check(self, request: CapabilityCheck) -> CapabilityCheckResult: ...


class EngineeringRepository(Protocol):
    def add_change(self, item: Change) -> None: ...
    def change(self, project_id: str, change_id: str) -> Change: ...
    def changes(self, project_id: str, revision_id: str | None = None) -> list[Change]: ...
    def save_finding(self, item: Finding, *, new: bool = False) -> None: ...
    def finding(self, project_id: str, finding_id: str) -> Finding: ...
    def findings(self, project_id: str) -> list[Finding]: ...
    def dependent_findings(self, project_id: str, source_id: str) -> list[Finding]: ...
    def add_coordination(self, item: Coordination) -> None: ...
    def coordination_records(self, project_id: str, finding_id: str) -> list[Coordination]: ...
    def save_recheck(self, item: ReCheck) -> None: ...
    def recheck(self, project_id: str, identity: str) -> ReCheck: ...
    def rechecks(self, project_id: str, finding_id: str) -> list[ReCheck]: ...
    def publication_digest(self, project_id: str, operation_id: str) -> str | None: ...
    def add_publication(self, project_id: str, operation_id: str, digest: str) -> None: ...
