"""Typed, project-scoped lifecycle records sharing the existing transaction boundary."""

from typing import Protocol

from app.domain.baselines import Baseline
from app.domain.project_sources import ProjectSource, ProjectSourceRevision


class ProjectLifecycleRepository(Protocol):
    def add_project_source(self, source: ProjectSource) -> None: ...
    def project_source(self, project_id: str, source_id: str) -> ProjectSource: ...
    def project_sources(self, project_id: str) -> list[ProjectSource]: ...
    def add_source_revision(self, revision: ProjectSourceRevision) -> None: ...
    def source_revision(
        self, project_id: str, source_id: str, revision_id: str
    ) -> ProjectSourceRevision: ...
    def source_revisions(self, project_id: str, source_id: str) -> list[ProjectSourceRevision]: ...
    def source_revision_by_hash(
        self, project_id: str, source_id: str, digest: str
    ) -> ProjectSourceRevision | None: ...
    def latest_source_revision(
        self, project_id: str, source_id: str
    ) -> ProjectSourceRevision | None: ...
    def add_baseline(self, baseline: Baseline) -> None: ...
    def baseline(self, project_id: str, baseline_id: str) -> Baseline: ...
    def baselines(self, project_id: str) -> list[Baseline]: ...
    def latest_baseline(self, project_id: str) -> Baseline | None: ...
