// Generated from frontend/openapi.json. DO NOT EDIT. Regenerate: pnpm generate.
export interface components { schemas: {
  "ActionExecution": { "operation_id": string; "proposal_id": string; "project_id": string; "before_version": number; "after_version": number; "status": "VERIFIED"; "mode": "simulated" | "external"; "principal_id": string; "result": string; "executed_at": string; };
  "ActionProposal": { "id": string; "operation_id": string; "project_id": string; "run_id": string; "generation": number; "snapshot_id": string; "snapshot_version": number; "work_package_id": string; "title": string; "risk": number; "resolution": components["schemas"]["ResolutionOption"]; "evidence_ids": Array<string>; "execution_mode": "simulated" | "external"; "created_at": string; };
  "AgentRun": { "id": string; "project_id": string; "event_id": (string | null); "status": "QUEUED" | "RUNNING" | "WAITING_APPROVAL" | "COMPLETED" | "FAILED" | "CANCELLED" | "EXPIRED"; "runtime": string; "runtime_execution_id": (string | null); "generation": number; "runtime_generation": number; "category": "coordination" | "document_parse" | "bim_import" | "optimization" | "vision" | "embedding_index"; "analysis_id": (string | null); "error": (string | null); "created_at": string; "updated_at": string; };
  "Analysis": { "id": string; "run_id": string; "snapshot": components["schemas"]["ProjectSnapshot"]; "impact": components["schemas"]["Impact"]; "evidence": Array<components["schemas"]["Evidence"]>; "findings": Array<components["schemas"]["Finding"]>; "constraints": Array<components["schemas"]["Constraint"]>; "readiness": Array<components["schemas"]["Readiness"]>; "reasoning_summary": string; "reasoning_mode": string; "created_at": string; };
  "Approval": { "id": string; "proposal_id": string; "principal_id": string; "principal_role": string; "level": "standard" | "strong"; "confirmation": string; "created_at": string; };
  "ApprovalRequest": { "strong"?: boolean; "confirmation"?: string; };
  "Area": { "id": string; "name": string; "floor": string; };
  "AuditRecord": { "id": string; "project_id": string; "action": string; "actor": string; "run_id": (string | null); "snapshot_id": (string | null); "operation_id": (string | null); "detail": Record<string, (string | number | boolean | null)>; "created_at": string; };
  "BIMElement": { "id": string; "name": string; "type": string; "storey": (string | null); "space": (string | null); "properties": Record<string, unknown>; "related_ids": Array<string>; "revision": string; };
  "BIMImport": { "kind": "bim_import"; "filename": string; "object_key": string; "content_hash": string; "base_revision": (string | null); "base_revision_bound": boolean; };
  "Baseline": { "name": string; "entries": Array<components["schemas"]["BaselineEntry"]>; "id": string; "project_id": string; "sequence": number; "accepted_by": string; "created_at": string; };
  "BaselineEntry": { "source_id": string; "revision_id": string; };
  "Body_import_document_api_projects__project_id__documents_post": { "file": string; };
  "Body_import_ifc_api_projects__project_id__bim_import_post": { "file": string; };
  "Body_upload_revision_api_projects__project_id__sources__source_id__revisions_post": { "file": string; "external_label"?: (string | null); };
  "Body_vision_api_projects__project_id__vision_post": { "file": string; "consent"?: boolean; };
  "Capability": { "name": string; "implementation": string; "status": "enabled" | "available_disabled" | "unavailable_dependency" | "unavailable_credential" | "unhealthy"; "enabled": boolean; "dependency_available": boolean; "credential_present": (boolean | null); "service_reachable": (boolean | null); "reason": string; "version": (string | null); };
  "CapabilityJob": { "id": string; "project_id": string; "requested_by": string; "request": (components["schemas"]["DocumentImport"] | components["schemas"]["BIMImport"] | components["schemas"]["OptimizationRequest"] | components["schemas"]["VisionRequest"] | components["schemas"]["EmbeddingIndexRequest-Output"]); "snapshot_id": (string | null); "result": (Record<string, unknown> | null); };
  "CapabilityResponse": { "capabilities": Array<components["schemas"]["Capability"]>; };
  "Constraint": { "id": string; "snapshot_id": string; "work_package_id": string; "kind": "design" | "predecessor" | "workforce" | "qualification" | "material" | "equipment" | "inspection"; "description": string; "evidence_ids": Array<string>; "resource_id": (string | null); "blocking": boolean; };
  "CreateArea": { "name": string; "floor"?: string; };
  "CreateBaseline": { "name": string; "entries": Array<components["schemas"]["BaselineEntry"]>; };
  "CreateProject": { "name": string; "description"?: string; "timezone"?: string; };
  "CreateProjectSource": { "name": string; "kind": "BIM" | "DOCUMENT" | "DRAWING" | "SCHEDULE"; };
  "CreateWorkPackage": { "name": string; "area_id": string; "discipline": string; "owner"?: string; };
  "Crew-Input": { "id": string; "workers": number; "qualifications": Array<string>; "available_from"?: number; "available_until"?: number; };
  "Crew-Output": { "id": string; "workers": number; "qualifications": Array<string>; "available_from": number; "available_until": number; };
  "DocumentChunk": { "id": string; "text": string; "page": (number | null); "location": (string | null); "source_hash": string; "parser": string; };
  "DocumentImport": { "kind": "document_parse"; "filename": string; "object_key": string; "content_hash": string; "document_id": string; };
  "DocumentMetadata": { "id": string; "project_id": string; "filename": string; "content_hash": string; "parser": string; "created_at": string; };
  "Effect": { "kind": "acknowledge_design" | "assign_crew" | "confirm_qualification" | "confirm_predecessor" | "confirm_material" | "confirm_equipment" | "record_inspection"; "work_package_id": string; "value": (string | number | boolean | Array<string>); "resource_id": (string | null); };
  "EmbeddingIndexRequest-Input": { "kind"?: "embedding_index"; "document_id": string; "chunk_ids"?: Array<string>; "consent"?: boolean; };
  "EmbeddingIndexRequest-Output": { "kind": "embedding_index"; "document_id": string; "chunk_ids": Array<string>; "consent": boolean; };
  "EventChange-Input": { "revision"?: (string | null); "available_workers"?: (number | null); "qualifications"?: (Array<string> | null); "predecessor_id"?: (string | null); "complete"?: (boolean | null); "resource_id"?: (string | null); "available"?: (boolean | null); "inspection_passed"?: (boolean | null); };
  "EventChange-Output": { "revision": (string | null); "available_workers": (number | null); "qualifications": (Array<string> | null); "predecessor_id": (string | null); "complete": (boolean | null); "resource_id": (string | null); "available": (boolean | null); "inspection_passed": (boolean | null); };
  "Evidence": { "id": string; "snapshot_id": string; "provider": string; "source_id": string; "source_revision": string; "observed_at": string; "work_package_id": (string | null); "element_ids": Array<string>; "page": (number | null); "location": (string | null); "fact": string; "quality": "structured" | "extracted" | "inferred"; };
  "ExecuteResponse": { "run_id": string; "operation_id": string; "queued": boolean; };
  "Finding": { "id": string; "snapshot_id": string; "work_package_id": string; "conclusion": string; "evidence_ids": Array<string>; "reasoning_summary": string; "confidence": number; "limitations": Array<string>; "created_at": string; };
  "HTTPValidationError": { "detail"?: Array<components["schemas"]["ValidationError"]>; };
  "Impact": { "work_package_ids": Array<string>; "area_ids": Array<string>; "element_ids": Array<string>; "disciplines": Array<string>; };
  "OptimizationRequest": { "kind": "optimization"; "problem": components["schemas"]["SchedulingProblem-Output"]; };
  "ProfileResponse": { "profile": string; "runtime": string; "reasoning": string; "storage": string; "database": string; "simulation": boolean; "authentication": string; };
  "Project": { "id": string; "name": string; "description": string; "timezone": string; };
  "ProjectEvent-Input": { "id"?: string; "project_id": string; "kind": "design_revision" | "workforce" | "predecessor" | "material" | "equipment" | "inspection" | "external"; "work_package_id": string; "title": string; "note"?: string; "source"?: string; "change"?: components["schemas"]["EventChange-Input"]; "observed_at"?: string; };
  "ProjectEvent-Output": { "id": string; "project_id": string; "kind": "design_revision" | "workforce" | "predecessor" | "material" | "equipment" | "inspection" | "external"; "work_package_id": string; "title": string; "note": string; "source": string; "change": components["schemas"]["EventChange-Output"]; "observed_at": string; };
  "ProjectSnapshot": { "id": string; "project_id": string; "version": number; "sources": Array<components["schemas"]["SourceRevision"]>; "captured_at": string; };
  "ProjectSource": { "id": string; "project_id": string; "name": string; "kind": "BIM" | "DOCUMENT" | "DRAWING" | "SCHEDULE"; "created_at": string; };
  "ProjectSourceRevision": { "id": string; "project_id": string; "source_id": string; "sequence": number; "external_label": (string | null); "original_filename": string; "sha256": string; "media_type": (string | null); "size_bytes": number; "storage_key": string; "import_status": "STORED"; "imported_at": string; };
  "ProjectSourceStatus": { "source": components["schemas"]["ProjectSource"]; "latest_revision_id": (string | null); "accepted_revision_id": (string | null); "baseline_id": (string | null); "has_pending_revision": boolean; };
  "ProjectState": { "project": components["schemas"]["Project"]; "version": number; "areas": Array<components["schemas"]["Area"]>; "work_packages": Array<components["schemas"]["WorkPackage"]>; "sources": Array<components["schemas"]["SourceRevision"]>; };
  "Readiness": { "work_package_id": string; "status": "READY" | "BLOCKED"; "constraint_ids": Array<string>; "snapshot_id": string; };
  "ResolutionOption": { "id": string; "title": string; "explanation": string; "constraint_ids": Array<string>; "effects": Array<components["schemas"]["Effect"]>; "resolver": string; };
  "RevisionUploadResult": { "revision": components["schemas"]["ProjectSourceRevision"]; "duplicate": boolean; };
  "ScheduleTask-Input": { "id": string; "duration": number; "workers"?: number; "qualifications"?: Array<string>; "predecessors"?: Array<string>; "equipment"?: Record<string, number>; "earliest"?: number; "latest_end"?: number; };
  "ScheduleTask-Output": { "id": string; "duration": number; "workers": number; "qualifications": Array<string>; "predecessors": Array<string>; "equipment": Record<string, number>; "earliest": number; "latest_end": number; };
  "SchedulingProblem-Input": { "tasks": Array<components["schemas"]["ScheduleTask-Input"]>; "crews": Array<components["schemas"]["Crew-Input"]>; "equipment_capacities"?: Record<string, number>; "horizon"?: number; };
  "SchedulingProblem-Output": { "tasks": Array<components["schemas"]["ScheduleTask-Output"]>; "crews": Array<components["schemas"]["Crew-Output"]>; "equipment_capacities": Record<string, number>; "horizon": number; };
  "SemanticMatch": { "document_id": string; "chunk_id": string; "text": string; "page": (number | null); "source_hash": string; "score": number; "model": string; "model_version": string; "dimensions": number; "test_only": boolean; };
  "SemanticQuery": { "query": string; "document_id"?: (string | null); "source_hash"?: (string | null); "limit"?: number; "consent"?: boolean; };
  "SourceRevision": { "source": string; "revision": string; "observed_at": string; };
  "StreamEvent": { "sequence": number; "run_id": string; "payload": Record<string, unknown>; };
  "ValidationError": { "loc": Array<(string | number)>; "msg": string; "type": string; "input"?: unknown; "ctx"?: Record<string, unknown>; };
  "VisionRequest": { "kind": "vision"; "object_key": string; "content_hash": string; "media_type": string; "source_id": string; "consent": boolean; };
  "WorkPackage": { "id": string; "name": string; "area_id": string; "discipline": string; "element_ids": Array<string>; "predecessors": Array<string>; "complete": boolean; "design_revision": string; "accepted_revision": string; "required_workers": number; "available_workers": number; "required_qualifications": Array<string>; "qualifications": Array<string>; "materials": Record<string, boolean>; "equipment": Record<string, boolean>; "inspection_passed": boolean; "owner": string; };
  "WorkspaceResponse": { "state": components["schemas"]["ProjectState"]; "analysis": (components["schemas"]["Analysis"] | null); "run": (components["schemas"]["AgentRun"] | null); "analysis_run": (components["schemas"]["AgentRun"] | null); "proposals": Array<components["schemas"]["ActionProposal"]>; "approvals": Array<components["schemas"]["Approval"]>; "events": Array<components["schemas"]["ProjectEvent-Output"]>; "audit": Array<components["schemas"]["AuditRecord"]>; "stale": boolean; };
}; }
