import { test } from "node:test";
import assert from "node:assert/strict";

globalThis.location = { hostname: "127.0.0.1" };
globalThis.window = {};
const storage = new Map();
globalThis.sessionStorage = {
  getItem: (key) => storage.get(key) ?? null,
  setItem: (key, value) => storage.set(key, value),
};
const { request, setToken, APIError, apiUrl, requestHeaders } =
  await import("../src/api/client.ts");

test("Headers instances preserve custom headers and use the current bearer token", async () => {
  setToken("contract-only-secret");
  globalThis.fetch = async (url, init) => {
    assert.equal(url, "/api/example");
    assert.equal(init.headers.get("X-Test"), "kept");
    assert.equal(
      init.headers.get("Authorization"),
      "Bearer contract-only-secret",
    );
    assert.equal(init.headers.get("Content-Type"), "application/json");
    return Response.json({ ok: true });
  };
  assert.deepEqual(
    await request("/api/example", {
      method: "POST",
      body: "{}",
      headers: new Headers({ "X-Test": "kept" }),
    }),
    { ok: true },
  );
  assert.equal(apiUrl("/api/example").includes("secret"), false);
});

test("multipart content type is generated by the browser, not forced to JSON", async () => {
  const body = new FormData();
  body.append("file", new Blob(["source"]), "source.txt");
  globalThis.fetch = async (_url, init) => {
    assert.equal(init.headers.has("Content-Type"), false);
    return Response.json({ imported: true });
  };
  await request("/api/upload", { method: "POST", body });
});

test("204 responses do not attempt JSON decoding", async () => {
  globalThis.fetch = async () => new Response(null, { status: 204 });
  assert.equal(await request("/api/empty"), undefined);
});

test("structured backend failures retain status and stable code", async () => {
  globalThis.fetch = async () =>
    Response.json(
      { code: "STALE_RESULT", detail: "Re-check required" },
      { status: 409 },
    );
  await assert.rejects(
    request("/api/action"),
    (error) =>
      error instanceof APIError &&
      error.status === 409 &&
      error.code === "STALE_RESULT",
  );
});

test("non-JSON proxy errors become readable API errors", async () => {
  globalThis.fetch = async () =>
    new Response("not JSON", { status: 502, statusText: "Bad Gateway" });
  await assert.rejects(
    request("/api/action"),
    (error) => error.message === "Bad Gateway",
  );
  assert.equal(requestHeaders().Authorization, "Bearer contract-only-secret");
});
